import adsk.core, adsk.fusion, adsk.cam, traceback
import os
import binascii
import tempfile

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        design = app.activeProduct
        
        if not design:
            ui.messageBox('No active Fusion design', 'No Design')
            return

        # 1. Define output location (automatically to Antigravity Data)
        output_dir = r'/Users/panda/Desktop/Antigravity Data'
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        doc_name = design.parentDocument.name if design.parentDocument.name else 'Untitled'
        # Sanitize filename (remove characters not allowed in filenames)
        safe_name = "".join([c for c in doc_name if c.isalnum() or c in (' ', '.', '_', '-')]).strip()
        output_py_path = os.path.join(output_dir, f'{safe_name}_exported.py')

        # 2. Export to temporary STL
        export_mgr = design.exportManager
        with tempfile.TemporaryDirectory() as tmp_dir:
            temp_stl_path = os.path.join(tmp_dir, 'temp_mesh.stl')
            
            # Create STL export options
            # Export the root component (entire assembly)
            stl_options = export_mgr.createSTLExportOptions(design.rootComponent, temp_stl_path)
            stl_options.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementHigh
            
            # Execute export
            res = export_mgr.execute(stl_options)
            
            # Read and hex-encode the STL
            with open(temp_stl_path, 'rb') as f:
                stl_binary = f.read()
            
            hex_data = binascii.hexlify(stl_binary).decode('utf-8')
            
            # 3. Generate the Python script content
            # Following the RECONSTRUCTION_GUIDE.md methodology
            script_template = f'''"""
Auto-generated Reconstruction Script
Generated by Fusion 360 Binary Exporter
Target: {design.parentDocument.name}
Methodology: Zero Volumetric Error (HEX Mesh Embedding)
"""

import os
import binascii

# Embedded Mesh Data (Binary STL hex-encoded)
HEX_DATA = "{hex_data}"

def reconstruct(output_path=None):
    """Decodes the embedded mesh and saves it to an STL file."""
    if output_path is None:
        # Use the directory of the current script for VSCode compatibility
        script_dir = os.path.dirname(os.path.abspath(__file__))
        filename = "{safe_name}_reconstructed.stl"
        output_path = os.path.join(script_dir, filename)
    
    print(f"--- RECONSTRUCTING CAD ---")
    print(f"Target: {{output_path}}")
    
    try:
        binary_data = binascii.unhexlify(HEX_DATA)
        with open(output_path, 'wb') as f:
            f.write(binary_data)
        print(f"SUCCESS: {{len(binary_data)}} bytes written.")
    except Exception as e:
        print(f"ERROR: Failed to write mesh data. {{e}}")
        return None
        
    return output_path

if __name__ == "__main__":
    path = reconstruct()
    if path:
        print(f"\\nReconstruction complete. You can now open the STL in your CAD viewer.")
'''
            
            # 4. Write the final Python script
            with open(output_py_path, 'w') as f:
                f.write(script_template)
            
            ui.messageBox(f'Successfully exported: {os.path.basename(output_py_path)}', 'Export Complete')

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
